exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
exec env TERM='dumb' INSIDE_EMACS='26.3,tramp:2.3.5.26.3' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
